services:
  eiq-genai-flow2.0-container-on-nxp-i.mx95:
    image: harbor.edgesync.cloud/nycu-cosmos-lab/eiq-genai-flow2.0-container-on-nxp-i.mx95
    container_name: eiq-genai-flow2.0-container-on-nxp-i.mx95
    privileged: true
    network_mode: host
    cap_add:
      - SYS_ADMIN
      - SYS_RAWIO
    devices:
      - /dev/neutron0
    volumes:
      - /usr/lib/python3.13/site-packages/onnxruntime:/usr/local/lib/python3.13/dist-packages/onnxruntime:ro
      - /usr/lib/python3.13/site-packages/onnxruntime-1.22.0.dist-info:/usr/local/lib/python3.13/dist-packages/onnxruntime-1.22.0.dist-info:ro
    stdin_open: true
    tty: true 
